name: Publish to PyPI
on:
  push:
    tags:
      - "v*"  # Trigger on tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Match your project's Python version

      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version  # Verify installation

      - name: Build and publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry build
          poetry publish --username __token__ --password $PYPI_TOKEN

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "v${{ github.ref_name }}"
          body_path: CHANGELOG.md
          files: |
            dist/*.whl
            dist/*.tar.gz